# Generated by Django 5.2.17 on 2026-09-07 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LichKham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lich_kham', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã đặt lịch')),
                ('ngay_kham', models.DateField(verbose_name='Ngày khám')),
                ('gio_kham', models.TimeField(verbose_name='Giờ khám')),
                ('trieu_chung', models.TextField(blank=True, null=True, verbose_name='Triệu chứng mô tả')),
                ('ly_do_kham', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do khám')),
                ('ten_benh_nhan', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tên người khám')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại liên hệ')),
                ('trang_thai', models.CharField(choices=[('Cho_xac_nhan', 'Chờ xác nhận'), ('Da_xac_nhan', 'Đã xác nhận'), ('Da_huy', 'Đã hủy'), ('Da_kham', 'Đã khám xong')], default='Cho_xac_nhan', max_length=20, verbose_name='Trạng thái lịch')),
                ('ghi_chu_bac_si', models.TextField(blank=True, null=True, verbose_name='Ghi chú/Chẩn đoán của bác sĩ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm đặt lịch')),
                ('bac_si', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_khams', to='doctors.bacsi', verbose_name='Bác sĩ phụ trách')),
                ('benh_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_khams', to=settings.AUTH_USER_MODEL, verbose_name='Bệnh nhân')),
                ('benh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_khams', to='hospitals.benhvien', verbose_name='Bệnh viện')),
                ('chuyen_khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_khams', to='hospitals.chuyenkhoa', verbose_name='Chuyên khoa')),
            ],
            options={
                'verbose_name': 'Lịch khám',
                'verbose_name_plural': 'Lịch khám',
                'ordering': ['-created_at'],
            },
        ),
    ]
