# Generated by Django 5.2.17 on 2026-09-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenKhoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuyen_khoa', models.CharField(max_length=150, verbose_name='Tên chuyên khoa')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả chuyên khoa')),
                ('bieu_tuong', models.CharField(default='bi-heart-pulse', max_length=50, verbose_name='Icon Bootstrap')),
            ],
            options={
                'verbose_name': 'Chuyên khoa',
                'verbose_name_plural': 'Chuyên khoa',
                'ordering': ['ten_chuyen_khoa'],
            },
        ),
        migrations.CreateModel(
            name='TinhThanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tinh', models.CharField(max_length=100, unique=True, verbose_name='Tên tỉnh/thành phố')),
            ],
            options={
                'verbose_name': 'Tỉnh / Thành phố',
                'verbose_name_plural': 'Tỉnh / Thành phố',
                'ordering': ['ten_tinh'],
            },
        ),
        migrations.CreateModel(
            name='BenhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_benh_vien', models.CharField(max_length=255, verbose_name='Tên bệnh viện')),
                ('dia_chi', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email liên hệ')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả bệnh viện')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('hinh_anh', models.CharField(blank=True, default='https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=800', max_length=500, null=True, verbose_name='Ảnh đại diện URL')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('chuyen_khoas', models.ManyToManyField(blank=True, related_name='benh_viens', to='hospitals.chuyenkhoa', verbose_name='Các chuyên khoa cung cấp')),
                ('tinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benh_viens', to='hospitals.tinhthanh', verbose_name='Tỉnh/Thành phố')),
            ],
            options={
                'verbose_name': 'Bệnh viện',
                'verbose_name_plural': 'Bệnh viện',
                'ordering': ['ten_benh_vien'],
            },
        ),
    ]
