# Generated by Django 5.2.17 on 2026-09-07 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=150, verbose_name='Họ và tên bác sĩ')),
                ('chuc_danh', models.CharField(default='Bác sĩ Chuyên khoa I', max_length=100, verbose_name='Chức danh / Học vị')),
                ('so_nam_kinh_nghiem', models.PositiveIntegerField(default=5, verbose_name='Số năm kinh nghiệm')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Tiểu sử & Chuyên môn')),
                ('anh_dai_dien', models.CharField(blank=True, default='https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600', max_length=500, null=True, verbose_name='Ảnh đại diện URL')),
                ('gia_kham', models.DecimalField(decimal_places=0, default=200000, max_digits=10, verbose_name='Giá khám tham khảo (VNĐ)')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Sẵn sàng nhận lịch')),
                ('benh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_sis', to='hospitals.benhvien', verbose_name='Bệnh viện công tác')),
                ('chuyen_khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bac_sis', to='hospitals.chuyenkhoa', verbose_name='Chuyên khoa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bac_si_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản người dùng')),
            ],
            options={
                'verbose_name': 'Bác sĩ',
                'verbose_name_plural': 'Bác sĩ',
                'ordering': ['ho_ten'],
            },
        ),
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày làm việc')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc')),
                ('so_luong_benh_nhan', models.PositiveIntegerField(default=5, verbose_name='Số lượng bệnh nhân tối đa/khung')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('bac_si', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_lam_viecs', to='doctors.bacsi', verbose_name='Bác sĩ')),
            ],
            options={
                'verbose_name': 'Lịch làm việc bác sĩ',
                'verbose_name_plural': 'Lịch làm việc bác sĩ',
                'ordering': ['ngay', 'gio_bat_dau'],
            },
        ),
    ]
